FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install && apt-get clean

COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "8000"]