FROM bitnami/spark:3.3
USER root

RUN apt-get update && apt-get install -y python3 python3-pip

COPY requirements_spark.txt /opt/spark/app/
RUN pip3 install --no-cache-dir -r /opt/spark/app/requirements_spark.txt

COPY spark_jobs /opt/spark/app/spark_jobs
COPY config /opt/spark/app/config
COPY mysql-connector-java-8.0.33.jar /opt/bitnami/spark/jars/

ENV PYTHONPATH=/opt/spark/app
WORKDIR /opt/spark/app